### ISSUE TITLE
Trojan Backdoor ? (??)

### ISSUE THREAD

**Issue by Zhongli0401** [PreviousAlone/Nnngram#24]
### Steps to reproduce

ah so i took the latest ci builds and i got something welp it says trojan backdoor
![image_2023-06-26_03-17-42](https://github.com/PreviousAlone/Nnngram/assets/76640596/b97c601e-19b2-45a6-9a29-66fcc2b54260)
![image_2023-06-26_03-17-57](https://github.com/PreviousAlone/Nnngram/assets/76640596/de717e51-911a-4979-bd0a-dbafd9d21361)

### Expected behaviour

backdoor

### Actual behaviour

idk

### Smartphone Information

for now not needed

### Nnngram Version

Nnngram-v9.6.6-preview-ea2dd06-arm64.apk

### Version requirement

- [X] I am using latest debug CI version of Nnngram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

no need

**Comment by Zhongli0401** [comment]
https://www.virustotal.com/gui/file/1a9d33c05876ff6826d47dd7cdbce00c76fbdb67de04cdc1c4369e512fc30e69?nocache=1

source has nothing

**Comment by rushiranpise** [comment]
Actually its because of these proguard rules [TMessagesProj/proguard-rules.pro]( https://github.com/PreviousAlone/Nnngram/commit/365c467991b904350307b60c99daff47320f4eb0#diff-480ccbae5a297e30919ae58726bfca69d824202779181e2432ba4e449acfd036) , if you build deobfuscated it will show these virus detected.

So,
with deobfuscated - virus are detected and you can use xposed based modules with it ( universal mostly)
with obfuscated  - virus are not detected and you cannot use xposed based modules with it (unless its specifically made for it)
it is same for nullgram repo also

it may have other benefits / drawbacks I ain't aware of !
